# Site settings
title: Peer 2 Peer University
email: admin@p2pu.org
description: "A University for the Web. Built by an open community.
LEARNING BY EVERYONE. FOR EVERYONE. ABOUT ALMOST ANYTHING. COMPLETELY FREE."
baseurl: "/"
url: "http://p2pu.org"

# Build settings
markdown: kramdown
permalink: pretty

collections:
- people
- projects

navigation:
- text: About
  url: /about/
  submenu:
  - text: Our people
    url: /people/
  - text: Our philopsophy
    url: http://info.p2pu.org/about/how-we-learn/
  - text: Credits
    url: /credits/
  - text: Terms
    url: /terms/
- text: Our work
  url: /work/
  submenu:
  - text: P2PU Schools
    url: /schools/
  - text: Current and past projects
    url: /projects/
  - text: Want to work with us?
    url: work_with_us
  - text: Workflow and strategic plan
    url: /workflow/
- text: Publications
  url: /publicaions/
- text: Connect with us
  url: /connect/






